# failure patterns knowledge base
# each pattern has: id, symptom, error_signals, root_cause, fix_steps, severity_range
# add more patterns as you encounter real incidents

FAILURE_PATTERNS = [
    {
        "id": "mongo_connection_pool",
        "symptom": "MongoDB connection pool exhausted, too many open connections, buffering timed out",
        "error_signals": [
            "MongooseError: Operation buffering timed out",
            "connection pool exhausted",
            "too many open connections",
            "MongoServerSelectionError",
        ],
        "root_cause": "MongoDB connection pool limit reached. Too many concurrent requests holding connections open without releasing them.",
        "fix_steps": [
            "Add maxPoolSize option to mongoose.connect()",
            "Check for unclosed connections in async functions",
            "Add connection timeout settings",
        ],
        "code_snippet": "mongoose.connect(uri, { maxPoolSize: 10, serverSelectionTimeoutMS: 5000 })",
        "severity_range": [3, 5],
    },
    {
        "id": "node_memory_leak",
        "symptom": "Node.js memory usage growing continuously, heap out of memory, process killed",
        "error_signals": [
            "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed",
            "JavaScript heap out of memory",
            "memory usage above 90%",
            "process killed OOM",
        ],
        "root_cause": "Memory leak in Node.js process. Common causes: event listeners not removed, closures holding references, large objects cached in memory.",
        "fix_steps": [
            "Use process.memoryUsage() to track heap growth",
            "Check for event listeners not being removed",
            "Look for global arrays/objects growing unbounded",
            "Consider using --max-old-space-size flag as temporary fix",
        ],
        "code_snippet": "node --max-old-space-size=512 server.js",
        "severity_range": [3, 5],
    },
    {
        "id": "express_unhandled_promise",
        "symptom": "Express server crashing on unhandled promise rejection, routes returning 500",
        "error_signals": [
            "UnhandledPromiseRejectionWarning",
            "unhandledRejection",
            "Cannot set headers after they are sent",
            "route handler crashed",
        ],
        "root_cause": "Async route handler throwing error without try/catch. Express does not handle async errors automatically in older versions.",
        "fix_steps": [
            "Wrap async route handlers in try/catch",
            "Add global unhandledRejection handler",
            "Use express-async-errors package",
        ],
        "code_snippet": "app.use((err, req, res, next) => { res.status(500).json({ error: err.message }) })",
        "severity_range": [2, 4],
    },
    {
        "id": "render_sleep_timeout",
        "symptom": "Render free tier service sleeping, cold start timeout, first request very slow",
        "error_signals": [
            "service unavailable",
            "502 bad gateway",
            "connection timeout on first request",
            "cold start",
            "spinning up",
        ],
        "root_cause": "Render free tier services spin down after 15 minutes of inactivity. First request after sleep takes 30-60 seconds to respond.",
        "fix_steps": [
            "Set up a cron job to ping the service every 10 minutes",
            "Use UptimeRobot free tier to keep service awake",
            "Upgrade to Render paid tier ($7/month) for always-on",
        ],
        "code_snippet": "# cron: */10 * * * * curl https://your-app.onrender.com/health",
        "severity_range": [1, 2],
    },
    {
        "id": "postgres_connection_limit",
        "symptom": "PostgreSQL too many connections, connection refused, pgbouncer limit reached",
        "error_signals": [
            "too many connections",
            "FATAL: remaining connection slots are reserved",
            "connection refused",
            "pgbouncer max connections",
        ],
        "root_cause": "PostgreSQL connection limit exceeded. Supabase free tier has a connection limit. Each serverless function/request opening a new connection without pooling.",
        "fix_steps": [
            "Use connection pooling via pgbouncer",
            "Use Supabase pooler URL instead of direct connection",
            "Reduce max connections in your ORM config",
        ],
        "code_snippet": "# use pooler URL: postgresql://user:pass@pooler.supabase.com:5432/postgres",
        "severity_range": [3, 5],
    },
    {
        "id": "high_response_time",
        "symptom": "API response time very high, requests taking more than 3 seconds, timeout errors",
        "error_signals": [
            "response time above 3000ms",
            "request timeout",
            "slow query",
            "ETIMEDOUT",
            "504 gateway timeout",
        ],
        "root_cause": "Slow database queries without indexes, N+1 query problem, or synchronous blocking operations in async code.",
        "fix_steps": [
            "Add database indexes on frequently queried columns",
            "Check for N+1 queries using query logging",
            "Move CPU-intensive work to background jobs",
            "Add query timeout limits",
        ],
        "code_snippet": "CREATE INDEX CONCURRENTLY idx_users_email ON users(email);",
        "severity_range": [2, 4],
    },
    {
        "id": "cors_error",
        "symptom": "CORS policy error, cross origin request blocked, preflight request failed",
        "error_signals": [
            "Access-Control-Allow-Origin",
            "CORS policy",
            "preflight request",
            "blocked by CORS",
            "cross-origin",
        ],
        "root_cause": "CORS middleware not configured correctly or missing. Frontend origin not whitelisted in backend CORS settings.",
        "fix_steps": [
            "Add frontend URL to CORS allowed origins",
            "Handle OPTIONS preflight requests",
            "Check CORS middleware is applied before routes",
        ],
        "code_snippet": "app.add_middleware(CORSMiddleware, allow_origins=['https://yourfrontend.com'])",
        "severity_range": [1, 3],
    },
    {
        "id": "disk_space_full",
        "symptom": "Disk space full, no space left on device, cannot write files or logs",
        "error_signals": [
            "no space left on device",
            "ENOSPC",
            "disk full",
            "cannot write",
            "storage limit exceeded",
        ],
        "root_cause": "Disk space exhausted. Common causes: log files growing unbounded, uploaded files not cleaned up, database growing too large.",
        "fix_steps": [
            "Delete old log files",
            "Set up log rotation",
            "Clean up temporary uploaded files",
            "Check database size and archive old records",
        ],
        "code_snippet": "# find large files: find / -size +100M -type f 2>/dev/null",
        "severity_range": [4, 5],
    },
    {
        "id": "redis_connection_failed",
        "symptom": "Redis connection refused, cache unavailable, session store error",
        "error_signals": [
            "Redis connection refused",
            "ECONNREFUSED 127.0.0.1:6379",
            "redis client error",
            "cache unavailable",
        ],
        "root_cause": "Redis server not running or connection config incorrect. Free tier Redis services (Upstash) have rate limits that can cause temporary connection failures.",
        "fix_steps": [
            "Check Redis server is running",
            "Verify Redis connection URL and port",
            "Add retry logic for Redis connections",
            "Check Upstash daily command limits",
        ],
        "code_snippet": "client = Redis(host=host, port=port, retry_on_timeout=True, socket_connect_timeout=5)",
        "severity_range": [2, 4],
    },
    {
        "id": "jwt_token_expired",
        "symptom": "JWT token expired, unauthorized 401 errors, users getting logged out",
        "error_signals": [
            "TokenExpiredError",
            "jwt expired",
            "401 unauthorized",
            "invalid token",
            "authentication failed",
        ],
        "root_cause": "JWT access tokens expiring and refresh token rotation not working correctly, or refresh token endpoint returning errors.",
        "fix_steps": [
            "Check token expiry time configuration",
            "Verify refresh token endpoint is working",
            "Add token refresh interceptor in frontend",
            "Check httpOnly cookie settings",
        ],
        "code_snippet": "// axios interceptor to refresh token on 401\naxios.interceptors.response.use(null, async (error) => { if (error.response.status === 401) { await refreshToken() } })",
        "severity_range": [2, 3],
    },
]